# Generated by Django 4.1.3 on 2022-11-04 09:44

import Influencer_Web.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='influencer_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(default='DEFAULT VALUE')),
                ('author_stats', djongo.models.fields.EmbeddedField(default='DEFAULT VALUE', model_container=Influencer_Web.models.Model)),
                ('video_list', djongo.models.fields.ArrayField(default='DEFAULT VALUE', model_container=Influencer_Web.models.VideoList)),
            ],
        ),
    ]
