#!/bin/sh

# Exit if any subcommand fails
set -e

DIR=$PWD

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m']
CLEAR_LINE='\r\033[K'

"${RED}==> Installing Homebrew for nodejs and python ==========================="
echo '# Set PATH, MANPATH, etc., for Homebrew.' >> /home/runner/.bash_profile
echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> /home/runner/.bash_profile
eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

# pwd
echo "${CLEAR_LINE}==> Installing nodejs =============================================="
sudo brew install node@16

echo "${CLEAR_LINE}==> Installing Python3.10 via Homebrew ======================"
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
sudo brew install python@3.10

# pwd
echo "${GREEN}==> Installing client npm dependencies ==========================="
npm install

# pwd
echo "${YELLOW}==> Installing server python dependencies ======================="
#python3 -m venv myvenv
#. myvenv/bin/activate
pip3 install -r requirements.txt
