name: Continuous Integration

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20 # Add this line here

    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install requirements
        run: npm install | pip3 install -r requirements.txt

      - name: Run tests & coverage
        run: npm run coverage
        env:
          CI: true

      # "coverage": "vitest run --coverage && coverage run -m pytest",
      - name: Upload to CodeClimate
        env:
          CC_TEST_REPORTER_ID: 197bd3ea34503bd3f3b767813ef33137c182c8b524f90b1611ce03a46c18791e
        run: |
          export GIT_BRANCH="${GITHUB_REF##*/}"
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter format-coverage -t coverage.py
          ./cc-test-reporter upload-coverage --id $CC_TEST_REPORTER_ID

