name: Continuous Integration

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20 # Add this line here

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install requirements
        run: npm install | pip3 install -r requirements.txt
      - name: Run tests
        run: npm run test
        env:
          CI: true
